### ISSUE TITLE
As a developer and user, I should have clear documentation about how Blockstack functions.

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/docs.blockstack#94]
@larrysalibra commented on [Thu Feb 15 2018](https://github.com/blockstack/blockstack/issues/417)

- Architecture of a “Blockstack App” — @shea256 https://github.com/blockstack/blockstack/issues/420
  - “What is a Blockstack App and how does it work?”
- High-level @muneeb-ali https://github.com/blockstack/blockstack/issues/419
- Authentication — Lead: @larrysalibra,  Document reviewer: @kantai https://github.com/blockstack/blockstack.js/issues/370
- Profiles —Lead: @yknl , Document reviewer: @larrysalibra https://github.com/blockstack/blockstack.js/issues/369
- Gaia Storage —Lead: @kantai , Document reviewer: @jcnelson @yknl   https://github.com/blockstack/gaia/issues/90
- Managing Data with Gaia Introduction —Lead: @cwackerfuss, Document reviewer: @jcnelson @larrysalibra   https://github.com/blockstack/blockstack/issues/427
- Blockstack Naming Service — Lead: @jcnelson , Document reviewer: @kantai https://github.com/blockstack/blockstack-core/issues/740
- Atlas — Lead: @jcnelson , Document reviewer: @muneeb-ali  https://github.com/blockstack/blockstack-core/issues/741
- Process — Lead: @larrysalibra Document reviewer: @cwackerfuss https://github.com/blockstack/blockstack/issues/418

---

@larrysalibra commented on [Wed Mar 07 2018](https://github.com/blockstack/blockstack/issues/417#issuecomment-371134055)

We've almost satisified this user story!

We still need: 
- [x] High-level docs  #419 from @muneeb-ali (not sure where we are on this)
- [x] Blockstack Apps docs #420 from @shea256 (a paper doc with a draft of this exists. Can we publish it for comment?)
- [x] To clarify if @kantai has reviewed and signed off on @jcnelson 's naming service docs https://github.com/blockstack/blockstack-core/issues/741
- [x] To clarify if @muneeb-ali has reviewed and signed off on @jcnelson 's Atlas docs https://github.com/blockstack/blockstack-core/issues/741 
- [x] Final review & sign off on @larrysalibra's auth docs by @kantai https://github.com/blockstack/blockstack.js/issues/370
- [x] Final review on process https://github.com/blockstack/blockstack/issues/418

**Comment by moxiegirl** [comment]
I believe our current structure satisfies this. If you think something is missing, please open a new single topic issue.  If there are multiples, I will gather them into an epic.
